version: "3"
services:
  # api:
  #   imaeg
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  # app:
  #     # build: .
  #     image: fastapi-cd:1.0
  #     volumes:
  #       - .:/code
  #     ports:
  #       - "8000:8000"
  #     depends_on:
  #       - postgres
  #       - redis
  # pgadmin:
  #     container_name: pgadmin
  #     image: dpage/pgadmin4
  #     environment:
  #       - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #       - PGADMIN_DEFAULT_PASSWORD=admin
  #     ports:
  #       - "5050:80"
  #     depends_on:
  #       - postgres
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
